name: Build ESP8266 firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Arduino files
      uses: actions/cache@v4
      with:
        path: |
          ~/.arduino15
          ~/Arduino/libraries
        key: arduino-${{ runner.os }}-v1

    # ✅ 直接下载，tag 带 v，文件名不带 v
    - name: Install Arduino CLI (direct download, pinned)
      run: |
        set -e
        CLI_VERSION=1.1.1
        CLI_TAG=v${CLI_VERSION}
        FILE=arduino-cli_${CLI_VERSION}_Linux_64bit.tar.gz
        URL=https://github.com/arduino/arduino-cli/releases/download/${CLI_TAG}/${FILE}
        echo "Downloading ${URL}"
        curl -fSLo /tmp/${FILE} "${URL}"
        tar -C /tmp -xzf /tmp/${FILE}
        sudo mv /tmp/arduino-cli /usr/local/bin/arduino-cli
        arduino-cli version

    - name: Prepare Arduino dirs
      run: |
        mkdir -p ~/Arduino/libraries
        arduino-cli config init
        arduino-cli config dump

    - name: Install ESP8266 core (pinned)
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266@3.1.2

    - name: Install libraries
      run: |
        arduino-cli lib install "WiFiManager@2.0.17-rc.2"

    - name: Compile firmware
      run: |
        # 你的目录/文件名：ESP8266_NAPT/ESP8266_NAPT.ino
        arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 ./ESP8266_NAPT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./ESP8266_NAPT/build/esp8266.esp8266.nodemcuv2/*.bin
